export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const ADD_USER_DETAILS = "ADD_USER_DETAILS"
export const ADD_USER = "ADD_USER"
export const EDIT_USER = "EDIT_USER"
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"
export const UPDATE_CONDITION = "UPDATE_CONDITION"